### ISSUE TITLE
Adding APKs to Releases

### ISSUE THREAD

**Issue by alpha4041** [mtrewartha/positional#109]
Hello, thanks a lot for creating this app, it's useful. I also posted it on [popMODS](https://t.me/popmods/).
I suggest adding the APKs to GitHub releases, giving people another option to install the application.

**Comment by mtrewartha** [comment]
Yeah, I'd be happy to include the APK in GitHub releases from now on. I need to automate releases at some point and I could tack the APK in there, but in the mean time I'll do it manually. In case I forget, feel free to ping me in here.

**Comment by mtrewartha** [comment]
Hey @alpha4041, the 3.1.2 release is out and I'm curious what publishing formats would be most useful for you here in GitHub. I think there are a number of ways to go about this, e.g. publish the AABs and let folks build their own APKs, publish universal APKs (defeats some of the purpose of smaller builds done in #247), or publish all the split APKs. Any thoughts/preferences?
