### ISSUE TITLE
Make the app light weight if possible 

### ISSUE THREAD

**Issue by Bobbydew1** [mtrewartha/positional#247]
Honestly i only use this app for the compass because, my phone is running on stock android 12 so it doesn't come with compass app and its the only compass app that i could find with beautiful ui, icon and name. 

So i suggest to make the app light weight IF possible, because I not using a compass app that weighs 100mb

**Comment by mtrewartha** [comment]
Ah, whoops. Thanks for bringing this to my attention! There's a simple fix- minification needs to be re-enabled. IIRC, I disabled it temporarily quite some time ago, but then I apparently forgot to re-enable it. I'm getting a PR up with what I think is a complete fix, but I'll need to test a bit more before releasing. Thanks again and I'll ping you in here once I release the fix!

**Comment by mtrewartha** [comment]
@Bobbydew1 This is rolling out to 5% of user's now and I'll ramp up as I see stability over the next couple days. Thanks again for the heads up and I hope you enjoy the slimmed down version!
