### ISSUE TITLE
What's the meaning of 362 degrees on compass?

### ISSUE THREAD

**Issue by djechelon** [mtrewartha/positional#4]
I found a weird behaviour of this app.

In compass mode, I moved the phone over a table to point to north. Moving the device very slowly yielded the following degrees readings:

- 358
- 359
- 360
- **361**
- **362**
- 3

360° is understandable (aircrafts take off and land on RWY 36 for example), but what's the purpose of 361°?
Wouldn't it be correct to start from 1 degree? Why starting from 3?

Have a nice day!

**Comment by mtrewartha** [comment]
Hey @djechelon, yeah, this was a bug. I noticed this awhile back and have corrected it, but I've been too busy to get a build out. It's coming, though!
